### ISSUE TITLE
Add live demo or screenshots

### ISSUE THREAD

**Issue by PedroHase** [christopher-caldwell/red-five#21]
Hey there, since this is a UI app, I suggest adding some meaningful screenshots instead of highly cropped ones so that users looking for a Redis dashboard UI can get a feeling of this app before downloading.

Bonuspoints if a demo /  dummy UI could be tested without having to download the app.

**Comment by christopher-caldwell** [comment]
@PedroHase I have added some screens to show it running. It would be very difficult to show the app running on a website as there would need to be some form of Redis instance available to run commands on. 

I see the benefit, but it's quite a low barrier of entry to get started.  

Let me know if the screens are sufficient, even if you elect not to use this. Your feedback is valuable. Thank you!
